import { build } from 'vite'
import { readFile, writeFile, mkdir } from 'node:fs/promises'

// Apps Script accepts a single HTML file. Bundle Vue locally for both hosts.
const result = await build({
  define: { 'process.env.NODE_ENV': '"production"' },
  build: {
    write: false,
    lib: { entry: 'frontend/src/main.js', name: 'Gaveta', formats: ['iife'] },
    cssCodeSplit: false,
  },
})
const outputs = (Array.isArray(result) ? result : [result]).flatMap(bundle => bundle.output)
const js = outputs.find(file => file.type === 'chunk').code.replace(/<\/script/gi, '<\\/script')
const css = outputs.filter(file => file.fileName.endsWith('.css')).map(file => file.source).join('\n')
const shell = await readFile('index.html', 'utf8')
const html = '<!-- Generated by npm run build. Edit frontend/src instead. -->\n' + shell
  .replace('</head>', () => `<style>${css}</style></head>`)
  .replace('<script type="module" src="/frontend/src/main.js"></script>', () => `<script>${js}</script>`)
await mkdir('dist', { recursive: true })
for (const target of [
  'dist/index.html',
  'meu_servidor/templates/index.html',
  'serverstocklart-main/meu_servidor/templates/index.html',
  'apps_script/index.html',
]) {
  await writeFile(target, html)
  console.log(`Built ${target}`)
}
